### ISSUE TITLE
tag cloud showing data from wikidata

### ISSUE THREAD

**Issue by addshore** [wbstack/queryservice-ui#3]
> ![image](https://user-images.githubusercontent.com/3308769/79609722-2684d500-80ef-11ea-8533-18c906faa028.png)
> 
> After the pull in [e29d243](https://github.com/wbstack/private/commit/e29d24338b33e545dd0d3912c1c7b53cf3e809ec) an API call to wikidata started happening

> Its an upstream issue! https://phabricator.wikimedia.org/T250528

**Comment by addshore** [comment]
This is fixed upstream now and just needs syncing and deploying for wbstack

**Comment by deer-wmde** [comment]
moved https://phabricator.wikimedia.org/T357117
